In [2]:
import pandas as pd
import os

In [3]:
#경로설정
#Path = os.path.join('Users','woosung','Gwangjin_project','data_original')
#Path1 = os.path.join('Users','woosung','Gwangjin_project','data_original','광진구주차장통합')
#Path2 = os.path.join('Users','woosung','Gwangjin_project','data_processing')

In [122]:
Path='data'
Path1='data/광진구주차장통합/'

# 1. 광진구 동별 인구현황 데이터

In [19]:
#맥북은 인코딩 방식을 utf-8사용하기 때문에 윈도우 방식인 cp949로 인코딩을 해준다.
df = pd.read_csv(f"{Path}/서울특별시_광진구_인구현황_20221231.csv",encoding = 'cp949')

In [20]:
df

,행정기관,계,인구수(남),인구수(여),지역(구성비),구성비(남),구성비(여),성비,세대수,세대당인구
0,광진구,337416,162541,174875,100.00,48.17,51.83,92.95,169291,1.99
1,중곡제1동,15299,7322,7977,4.53,2.17,2.36,91.79,8504,1.80
2,중곡제2동,20999,9903,11096,6.22,2.93,3.29,89.25,10656,1.97
3,중곡제3동,15945,7897,8048,4.73,2.34,2.39,98.12,8513,1.87
4,중곡제4동,28035,13715,14320,8.31,4.06,4.24,95.78,13122,2.14
5,능동,11180,5134,6046,3.31,1.52,1.79,84.92,6406,1.75
6,구의제1동,23387,11143,12244,6.93,3.30,3.63,91.01,13077,1.79
7,구의제2동,26043,12511,13532,7.72,3.71,4.01,92.45,11517,2.26
8,구의제3동,28211,13309,14902,8.36,3.94,4.42,89.31,12079,2.34
9,광장동,34168,16524,17644,10.13,4.90,5.23,93.65,11814,2.89
10,자양제1동,21862,10646,11216,6.48,3.16,3.32,94.92,11913,1.84
11,자양제2동,23946,11612,12334,7.10,3.44,3.66,94.15,10887,2.20
12,자양제3동,27553,13166,14387,8.17,3.90,4.26,91.51,11009,2.50
13,자양제4동,17926,8915,9011,5.31,2.64,2.67,98.93,10209,1.76
14,화양동,23437,11141,12296,6.95,3.30,3.64,90.61,18185,1.29
15,군자동,19425,9603,9822,5.76,2.85,2.91,97.77,11400,1.70

***

# 2. 광진구 공영주차장 정보

In [155]:
#맥북은 인코딩 방식을 utf-8사용하기 때문에 윈도우 방식인 cp949로 인코딩을 해준다.
df1 = pd.read_csv(f"{Path}/서울특별시 광진구_공영주차장 정보_20220118.csv",encoding = 'cp949')

# 2-1. 전처리

In [156]:
#nan값 행 확인
df1[df1["주차요금 종일"].isnull()]

,연번,운영개시일,동명,시설명,위치,부지면적,주차면수 소계,주차면수 노상,주차면수 노외,거주자,공영,급지,주차요금 5분당,주차요금 주간,주차요금 야간,주차요금 종일,시설규모,비고
0,1,2010-09,중곡1동,중곡제일전통시장 공영,중곡1동 221-6,695,21,0.0,21.0,NaN,O,2,250원,NaN,3만원,NaN,NaN,구유지(지역경제과·위탁)
26,27,2010-06,자양1동,자양전통시장 공영,자양1동 631-18,447.5,24,NaN,24.0,NaN,O,2,250원,NaN,3만원,NaN,2층,구유지(지역경제과·위탁)

In [157]:
#nan값 0으로 바꾸기
df1["부지면적"] = df1["부지면적"].fillna(0)
df1["주차면수 노상"] = df1["주차면수 노상"].fillna(0)
df1["주차면수 노외"] = df1["주차면수 노외"].fillna(0)
df1["주차요금 5분당"] = df1["주차요금 5분당"].fillna(0)
df1["주차요금 주간"] = df1["주차요금 주간"].fillna(0)
df1["주차요금 야간"] = df1["주차요금 야간"].fillna(0)
df1["주차요금 종일"] = df1["주차요금 종일"].fillna(30000)

In [158]:
#nan값 다른 문자로 바꾸기
df1["거주자"] = df1["거주자"].fillna('X')
df1["공영"] = df1["공영"].fillna('X')
df1["시설규모"] = df1["시설규모"].fillna('1층1단')

In [159]:
#(만원)삭제하기, (원)삭제하기
df1['주차요금 5분당'] = df1['주차요금 5분당'].str.replace('원', '')
df1['주차요금 주간'] = df1['주차요금 주간'].str.replace('만원', '0000')
df1['주차요금 야간'] = df1['주차요금 야간'].str.replace('만원', '0000')
df1['주차요금 종일'] = df1['주차요금 종일'].str.replace('만원', '0000')

In [ ]:
df1.to_csv(f"/{Path2}/서울특별시 광진구_공영주차장 정보_20220118.csv", index = False)

# 2-2 . 필요없는 (속성)열 제거

In [160]:
df1.drop(labels=['연번','운영개시일','거주자','공영','급지','시설규모','비고','주차면수 노상','주차면수 노외',
                 '주차요금 5분당','주차요금 주간','주차요금 야간','부지면적'],axis=1,inplace=True)

In [161]:
df1

      동명               시설명             위치  주차면수 소계 주차요금 종일
0   중곡1동       중곡제일전통시장 공영     중곡1동 221-6       21     NaN
1   중곡2동               장신구    중곡2동 133-10       22   50000
2   중곡2동            중곡동복개천   중곡2동 150-196       78  100000
3   중곡3동          중곡3동마을공원     중곡3동 195-1      162   50000
4   중곡3동            중곡체육센터     중곡3동 168-8        6   50000
5   중곡4동             신성시장길    중곡4동 453 일대       33  100000
6   중곡4동               새오름    중곡4동 143-70        7   50000
7   중곡4동              용마산남      중곡4동 69-2       25   50000
8   중곡4동            긴고랑길공영    중곡4동 72-1 외       53   50000
9   중곡4동               해오름     중곡4동 87-14       20   50000
10  중곡4동  뻥튀기골주차장(용마공원주차장)   중곡4동 176-110       18   50000
11  중곡4동     중곡4동 599-6 인근     면목4동 산75-2        9   50000
12  중곡4동             한림대부지   중곡4동 176-119        8   50000
13    능동              능동공영         능동 205       77   50000
14    능동              능동공동         능동 377       25   50000
15  구의1동           구의1동 공영    구의1동 243-78      172   80000
16  구의1동              구의번영     구의1동 230-7       34   50000
17  구의2동        구의2동 주택가공동      구의2동 30-9       90   50000
18  구의2동              광문학당      구의2동 72-8       12   50000
19  구의2동         공원(동의초인근)         구의2동 6       11   40000
20  구의3동           동서울길 공영  구의3동 609-1 일대       94  100000
21  구의3동           구의3동 공영    구의3동 219-15      159   80000
22  구의3동         올림픽대교(시영)     구의3동 623-1       19   40000
23   광장동                세촌      광장동 275-5        7   40000
24   광장동             광장공동    광장동 394-43 외        8   50000
25   광장동               큰나루        광장동 126       13  100000
26  자양1동         자양전통시장 공영    자양1동 631-18       24     NaN
27  자양2동               유수지       자양2동 594      281   50000
28  자양3동             송림식당길    자양3동 712 일대       94   90000
29  자양4동           자양4동 공영       자양4동 5-5       86  100000
30  자양4동              행복제2      자양4동 10-2       53   50000
31   화양동        느티나무(화양공동)     화양동 110-67       27   50000
32   화양동            화양동 공영       화양동 63-2       44   80000
33   화양동          화양동 마을마당      화양동 523-2        6   50000
34   군자동            군자동 공영       군자동 2-41       53   50000
35   군자동           광진광장 공영        군자동 374       36  120000

In [162]:
df1.isnull().sum()

동명         0
시설명        0
위치         0
주차면수 소계    0
주차요금 종일    2
dtype: int64

In [163]:
df1=df1.fillna(30000)

In [164]:
df1

      동명               시설명             위치  주차면수 소계 주차요금 종일
0   중곡1동       중곡제일전통시장 공영     중곡1동 221-6       21   30000
1   중곡2동               장신구    중곡2동 133-10       22   50000
2   중곡2동            중곡동복개천   중곡2동 150-196       78  100000
3   중곡3동          중곡3동마을공원     중곡3동 195-1      162   50000
4   중곡3동            중곡체육센터     중곡3동 168-8        6   50000
5   중곡4동             신성시장길    중곡4동 453 일대       33  100000
6   중곡4동               새오름    중곡4동 143-70        7   50000
7   중곡4동              용마산남      중곡4동 69-2       25   50000
8   중곡4동            긴고랑길공영    중곡4동 72-1 외       53   50000
9   중곡4동               해오름     중곡4동 87-14       20   50000
10  중곡4동  뻥튀기골주차장(용마공원주차장)   중곡4동 176-110       18   50000
11  중곡4동     중곡4동 599-6 인근     면목4동 산75-2        9   50000
12  중곡4동             한림대부지   중곡4동 176-119        8   50000
13    능동              능동공영         능동 205       77   50000
14    능동              능동공동         능동 377       25   50000
15  구의1동           구의1동 공영    구의1동 243-78      172   80000
16  구의1동              구의번영     구의1동 230-7       34   50000
17  구의2동        구의2동 주택가공동      구의2동 30-9       90   50000
18  구의2동              광문학당      구의2동 72-8       12   50000
19  구의2동         공원(동의초인근)         구의2동 6       11   40000
20  구의3동           동서울길 공영  구의3동 609-1 일대       94  100000
21  구의3동           구의3동 공영    구의3동 219-15      159   80000
22  구의3동         올림픽대교(시영)     구의3동 623-1       19   40000
23   광장동                세촌      광장동 275-5        7   40000
24   광장동             광장공동    광장동 394-43 외        8   50000
25   광장동               큰나루        광장동 126       13  100000
26  자양1동         자양전통시장 공영    자양1동 631-18       24   30000
27  자양2동               유수지       자양2동 594      281   50000
28  자양3동             송림식당길    자양3동 712 일대       94   90000
29  자양4동           자양4동 공영       자양4동 5-5       86  100000
30  자양4동              행복제2      자양4동 10-2       53   50000
31   화양동        느티나무(화양공동)     화양동 110-67       27   50000
32   화양동            화양동 공영       화양동 63-2       44   80000
33   화양동          화양동 마을마당      화양동 523-2        6   50000
34   군자동            군자동 공영       군자동 2-41       53   50000
35   군자동           광진광장 공영        군자동 374       36  120000

In [165]:
dong_dic={
    '중곡동':10100,
    '중곡1동':10100,
    '중곡2동':10100,
    '중곡3동':10100,
    '중곡4동':10100,
    '능동':10200,
    '구의동':10300,
    '구의1동':10300,
    '구의2동':10300,
    '구의3동':10300,
    '구의4동':10300,
    '광장동':10400,
    '자양동':10500,
    '자양1동':10500,
    '자양2동':10500,
    '자양3동':10500,
    '자양4동':10500,
    '화양동':10700,
    '군자동':10900
}

In [166]:
df1['동명']=df1['동명'].map(dong_dic)

In [167]:
lat_dic={'경도':[127.081744,127.084000,127.086222,127.084660,127.084782,127.089886,127.090864,127.092061,127.094478,127.091651,
               127.089378,127.089358,127.088880,127.080217,127.079673,127.087849,127.089010,127.092823,127.090237,
               127.097339,127.091634,127.091347,127.098904,127.105526,127.101528,127.110315,127.081576,127.078268,
               127.076033,127.068162,127.066308,127.071247,127.071155,127.075229,127.076913,127.735722]}
lon_dic={'위도':[37.5638634,37.5564016,37.5601391,37.5699070,37.5677625,37.5572893,37.5613791,37.5591167,37.5638630,37.5570357,37.5683178,
               37.5702820,37.5683452,37.5540256,37.5530619,37.5382528,37.5442346,37.5529173,37.5479277,37.5533101,37.5331504,37.5391332,
               37.5387758,37.5486270,37.5464231,37.5503166,37.5337793,37.5295198,37.5344317,37.5386621,37.5400056,37.5465980,37.5452826,
               37.5450549,37.5540548,34.7421598]}
lat=pd.DataFrame(lat_dic)
lon=pd.DataFrame(lon_dic)

In [168]:
df1['경도']=lat
df1['위도']=lon
df1=df1.drop(columns='위치',axis=1)

In [169]:
df1

       동명               시설명  주차면수 소계 주차요금 종일          경도         위도
0   10100       중곡제일전통시장 공영       21   30000  127.081744  37.563863
1   10100               장신구       22   50000  127.084000  37.556402
2   10100            중곡동복개천       78  100000  127.086222  37.560139
3   10100          중곡3동마을공원      162   50000  127.084660  37.569907
4   10100            중곡체육센터        6   50000  127.084782  37.567763
5   10100             신성시장길       33  100000  127.089886  37.557289
6   10100               새오름        7   50000  127.090864  37.561379
7   10100              용마산남       25   50000  127.092061  37.559117
8   10100            긴고랑길공영       53   50000  127.094478  37.563863
9   10100               해오름       20   50000  127.091651  37.557036
10  10100  뻥튀기골주차장(용마공원주차장)       18   50000  127.089378  37.568318
11  10100     중곡4동 599-6 인근        9   50000  127.089358  37.570282
12  10100             한림대부지        8   50000  127.088880  37.568345
13  10200              능동공영       77   50000  127.080217  37.554026
14  10200              능동공동       25   50000  127.079673  37.553062
15  10300           구의1동 공영      172   80000  127.087849  37.538253
16  10300              구의번영       34   50000  127.089010  37.544235
17  10300        구의2동 주택가공동       90   50000  127.092823  37.552917
18  10300              광문학당       12   50000  127.090237  37.547928
19  10300         공원(동의초인근)       11   40000  127.097339  37.553310
20  10300           동서울길 공영       94  100000  127.091634  37.533150
21  10300           구의3동 공영      159   80000  127.091347  37.539133
22  10300         올림픽대교(시영)       19   40000  127.098904  37.538776
23  10400                세촌        7   40000  127.105526  37.548627
24  10400             광장공동         8   50000  127.101528  37.546423
25  10400               큰나루       13  100000  127.110315  37.550317
26  10500         자양전통시장 공영       24   30000  127.081576  37.533779
27  10500               유수지      281   50000  127.078268  37.529520
28  10500             송림식당길       94   90000  127.076033  37.534432
29  10500           자양4동 공영       86  100000  127.068162  37.538662
30  10500              행복제2       53   50000  127.066308  37.540006
31  10700        느티나무(화양공동)       27   50000  127.071247  37.546598
32  10700            화양동 공영       44   80000  127.071155  37.545283
33  10700          화양동 마을마당        6   50000  127.075229  37.545055
34  10900            군자동 공영       53   50000  127.076913  37.554055
35  10900           광진광장 공영       36  120000  127.735722  34.742160

In [18]:
df1.to_csv(f"/{Path2}/서울특별시 광진구_공영주차장 정보_20220118.csv", index = False)

***

# 4. 광진구 야간개방 주차장

In [109]:
df3 = pd.read_csv(f"{Path}/서울특별시 광진구_야간개방주차장_20221227.csv", encoding = 'utf-8', header=1)

In [110]:
df3

,일련번호,주차장고유값,주차장명,시도명칭,시군구명칭,법정읍면동명칭,번지,호,도로명 이름,건물 번호,...,무료 개방여부,수시주차가능여부,운영방식,거주자-주간(월)금액,거주자-야간(월)금액,거주자-전일(월)금액,시작시간,종료시간,특이사항,구축기준일
0,1,5533775,광장동IoT공유주차장,서울특별시,광진구,광장동,102,NaN,아차산로78길,75,...,0,0,2,30000.0,20000.0,40000.0,0,2400,NaN,44890
1,2,5533773,광장동IoT공유주차장,서울특별시,광진구,광장동,102,NaN,아차산로78길,75,...,0,0,2,30000.0,20000.0,40000.0,0,2400,NaN,44890
2,3,5533772,광장동IoT공유주차장,서울특별시,광진구,광장동,102,NaN,아차산로78길,75,...,0,0,2,30000.0,20000.0,40000.0,0,2400,NaN,44890
3,4,4759402,102 노상주차장,서울특별시,광진구,광장동,102,NaN,아차산로78길,75,...,0,0,2,30000.0,20000.0,40000.0,0,2400,NaN,44890
4,5,4755783,102 거주자우선주차장,서울특별시,광진구,광장동,102,NaN,아차산로78길,75,...,0,0,2,30000.0,20000.0,40000.0,0,2400,NaN,44890
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1579,1580,5532177,526-34 거주자우선주차장,서울특별시,광진구,화양동,526,34.0,아차산로39길,38-7,...,0,0,2,30000.0,20000.0,40000.0,0,2400,NaN,44890
1580,1581,5532176,526-34 거주자우선주차장,서울특별시,광진구,화양동,526,34.0,아차산로39길,38-7,...,0,0,2,30000.0,20000.0,40000.0,0,2400,NaN,44890
1581,1582,5532175,526-34 거주자우선주차장,서울특별시,광진구,화양동,526,34.0,아차산로39길,38-7,...,0,0,2,30000.0,20000.0,40000.0,0,2400,NaN,44890
1582,1583,5532174,526-34 거주자우선주차장,서울특별시,광진구,화양동,526,34.0,아차산로39길,38-7,...,0,0,2,30000.0,20000.0,40000.0,0,2400,NaN,44890
1583,1584,5532140,526-34 거주자우선주차장,서울특별시,광진구,화양동,526,34.0,아차산로39길,38-7,...,0,0,2,30000.0,20000.0,40000.0,0,2400,NaN,44890

In [111]:
df3.isnull().sum()

일련번호              0
주차장고유값            0
주차장명              0
시도명칭              0
시군구명칭             0
법정읍면동명칭           0
번지                0
호               319
도로명 이름           95
건물 번호           123
경도                0
위도                0
개방면수              0
무료 개방여부           0
수시주차가능여부          0
운영방식              0
거주자-주간(월)금액      57
거주자-야간(월)금액      58
거주자-전일(월)금액      58
시작시간              0
종료시간              0
특이사항           1579
구축기준일             0
dtype: int64

# 4-1. 전처리

In [112]:
df3[df3['무료 개방여부']==1]

,일련번호,주차장고유값,주차장명,시도명칭,시군구명칭,법정읍면동명칭,번지,호,도로명 이름,건물 번호,...,무료 개방여부,수시주차가능여부,운영방식,거주자-주간(월)금액,거주자-야간(월)금액,거주자-전일(월)금액,시작시간,종료시간,특이사항,구축기준일
169,170,4960105,서울광장초등학교,서울특별시,광진구,광장동,389,1.0,광장로1길,27,...,1,0,9,NaN,NaN,NaN,0,730,NaN,44890
191,192,5525955,29-21 노상주차장,서울특별시,광진구,구의동,29,21.0,자양로51길,11-8,...,1,1,1,NaN,NaN,NaN,0,0,NaN,44890
267,268,5529929,238-2 노상주차장,서울특별시,광진구,구의동,238,2.0,능동로36길,82,...,1,0,2,NaN,NaN,NaN,0,0,NaN,44890
268,269,5529928,238-2 노상주차장,서울특별시,광진구,구의동,238,2.0,능동로36길,82,...,1,0,2,NaN,NaN,NaN,0,0,NaN,44890
269,270,5529927,238-2 노상주차장,서울특별시,광진구,구의동,238,2.0,능동로36길,82,...,1,0,2,NaN,NaN,NaN,0,0,NaN,44890
270,271,5529926,238-2 노상주차장,서울특별시,광진구,구의동,238,2.0,능동로36길,82,...,1,0,2,NaN,NaN,NaN,0,0,NaN,44890
271,272,5529925,238-2 노상주차장,서울특별시,광진구,구의동,238,2.0,능동로36길,82,...,1,0,2,NaN,NaN,NaN,0,0,NaN,44890
272,273,5529924,238-2 노상주차장,서울특별시,광진구,구의동,238,2.0,능동로36길,82,...,1,0,2,NaN,NaN,NaN,0,0,NaN,44890
273,274,5529923,238-2 노상주차장,서울특별시,광진구,구의동,238,2.0,능동로36길,82,...,1,0,2,NaN,NaN,NaN,0,0,NaN,44890
274,275,5529922,238-2 노상주차장,서울특별시,광진구,구의동,238,2.0,능동로36길,82,...,1,0,2,NaN,NaN,NaN,0,0,NaN,44890
275,276,5529921,238-2 노상주차장,서울특별시,광진구,구의동,238,2.0,능동로36길,82,...,1,0,2,NaN,NaN,NaN,0,0,NaN,44890
276,277,5529920,238-2 노상주차장,서울특별시,광진구,구의동,238,2.0,능동로36길,82,...,1,0,2,NaN,NaN,NaN,0,0,NaN,44890
277,278,5529919,238-2 노상주차장,서울특별시,광진구,구의동,238,2.0,능동로36길,82,...,1,0,2,NaN,NaN,NaN,0,0,NaN,44890
278,279,5529918,238-2 노상주차장,서울특별시,광진구,구의동,238,2.0,능동로36길,82,...,1,0,2,NaN,NaN,NaN,0,0,NaN,44890
279,280,5529904,238-2 노상주차장,서울특별시,광진구,구의동,238,2.0,능동로36길,82,...,1,0,2,NaN,NaN,NaN,0,0,NaN,44890
328,329,1629386,동서울호텔길(노상),서울특별시,광진구,구의동,609,1.0,구의강변로,NaN,...,1,1,1,NaN,NaN,NaN,1800,2400,6시 이후 무료(시설공단확인완료),44890
405,406,4757989,비전빌딩옆노상주차장,서울특별시,광진구,군자동,1,11.0,능동로,275,...,1,1,1,30000.0,20000.0,40000.0,0,0,NaN,44890
406,407,4757988,비전빌딩옆노상주차장,서울특별시,광진구,군자동,1,11.0,능동로,275,...,1,1,1,30000.0,20000.0,40000.0,0,0,NaN,44890
407,408,4757688,비전빌딩옆노상주차장,서울특별시,광진구,군자동,1,11.0,능동로,275,...,1,1,1,30000.0,20000.0,40000.0,0,0,NaN,44890
408,409,4756440,비전빌딩옆노상주차장,서울특별시,광진구,군자동,1,11.0,능동로,275,...,1,1,1,30000.0,20000.0,40000.0,0,0,NaN,44890
409,410,4814713,27-4 노상주차장,서울특별시,광진구,군자동,27,4.0,능동로,257,...,1,1,1,30000.0,20000.0,40000.0,0,0,NaN,44890
410,411,4809600,27-4 노상주차장,서울특별시,광진구,군자동,27,4.0,능동로,257,...,1,1,1,30000.0,20000.0,40000.0,0,0,NaN,44890
412,413,4756761,27-4 노상주차장,서울특별시,광진구,군자동,27,4.0,능동로,257,...,1,1,1,30000.0,20000.0,40000.0,0,0,NaN,44890
414,415,4756760,45-11 노상주차장,서울특별시,광진구,군자동,45,11.0,능동로29가길,3,...,1,1,1,30000.0,20000.0,40000.0,0,0,NaN,44890
415,416,4756441,45-11 노상주차장,서울특별시,광진구,군자동,45,11.0,능동로29가길,3,...,1,1,1,30000.0,20000.0,40000.0,0,0,NaN,44890
416,417,4738706,45-11 노상주차장,서울특별시,광진구,군자동,45,11.0,능동로29가길,3,...,1,1,1,30000.0,20000.0,40000.0,0,0,NaN,44890
420,421,4806525,195-18 노상주차장,서울특별시,광진구,군자동,195,18.0,동일로56길,11,...,1,1,1,30000.0,20000.0,40000.0,0,0,NaN,44890
421,422,4758400,280 노상주차장,서울특별시,광진구,군자동,280,NaN,능동로21길,38,...,1,1,1,30000.0,20000.0,40000.0,0,0,NaN,44890
452,453,4738276,466-16 거주자우선주차장,서울특별시,광진구,군자동,466,16.0,천호대로104길,8,...,1,0,2,30000.0,20000.0,40000.0,0,0,NaN,44890
548,549,4755108,어린이대공원노상주차장,서울특별시,광진구,능동,257,25.0,천호대로122길,33,...,1,1,1,NaN,NaN,NaN,0,0,NaN,44890
549,550,4754428,어린이대공원노상주차장,서울특별시,광진구,능동,257,25.0,천호대로122길,33,...,1,1,1,NaN,NaN,NaN,0,0,NaN,44890
551,552,4754425,어린이대공원노상주차장,서울특별시,광진구,능동,257,25.0,천호대로122길,33,...,1,1,1,NaN,NaN,NaN,0,0,NaN,44890
552,553,4754424,어린이대공원노상주차장,서울특별시,광진구,능동,257,25.0,천호대로122길,33,...,1,1,1,NaN,NaN,NaN,0,0,NaN,44890
553,554,4736651,어린이대공원노상주차장,서울특별시,광진구,능동,257,25.0,천호대로122길,33,...,1,1,1,NaN,NaN,NaN,0,0,NaN,44890
554,555,5527869,어린이대공원노상주차장,서울특별시,광진구,능동,258,5.0,천호대로124길,60-6,...,1,1,1,NaN,NaN,NaN,0,0,NaN,44890
555,556,5527868,어린이대공원노상주차장,서울특별시,광진구,능동,258,5.0,천호대로124길,60-6,...,1,1,1,NaN,NaN,NaN,0,0,NaN,44890
556,557,5527867,어린이대공원노상주차장,서울특별시,광진구,능동,258,5.0,천호대로124길,60-6,...,1,1,1,NaN,NaN,NaN,0,0,NaN,44890
557,558,4759422,어린이대공원노상주차장,서울특별시,광진구,능동,258,5.0,천호대로124길,60-6,...,1,1,1,NaN,NaN,NaN,0,0,NaN,44890
558,559,4759386,어린이대공원노상주차장,서울특별시,광진구,능동,258,19.0,천호대로124길,48,...,1,1,1,NaN,NaN,NaN,0,0,NaN,44890
559,560,4759385,258-19 거주자우선주차장,서울특별시,광진구,능동,258,19.0,천호대로124길,48,...,1,0,2,30000.0,20000.0,40000.0,0,0,NaN,44890
560,561,4755106,어린이대공원노상주차장,서울특별시,광진구,능동,258,12.0,천호대로124길,40,...,1,1,1,NaN,NaN,NaN,0,0,NaN,44890
561,562,4754422,어린이대공원노상주차장,서울특별시,광진구,능동,258,19.0,천호대로124길,48,...,1,1,1,NaN,NaN,NaN,0,0,NaN,44890
742,743,1575781,송림식당길(노상),서울특별시,광진구,자양동,227,137.0,자양번영로,79,...,1,1,1,NaN,NaN,NaN,1800,2400,6시 이후 무료(시설공단확인완료),44890
1183,1184,1512341,중곡복개천 공영 노상,서울특별시,광진구,중곡동,150,196.0,긴고랑로,NaN,...,1,1,2,NaN,NaN,NaN,1800,900,6시 이후 무료(시설공단확인완료),44890
1338,1339,1512340,중곡복개천 공영B 노상,서울특별시,광진구,중곡동,277,2.0,긴고랑로,NaN,...,1,1,2,NaN,NaN,NaN,1800,900,"6시 이후 무료(시설공단확인완료), 일요일공휴일 전일개방",44890

In [113]:
#nan값 0으로 바꾸기
df3["거주자-전일(월)금액"] = df3["거주자-전일(월)금액"].fillna(0)

# 4-2 . 필요없는 (속성)열 제거

In [114]:
df3=df3[['주차장고유값','주차장명','경도','위도','거주자-전일(월)금액','법정읍면동명칭']]

In [115]:
df3['거주자-전일(월)금액']=df3['거주자-전일(월)금액'].astype(int)

C:\Users\shjo\AppData\Local\Temp\ipykernel_11476\2837637102.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['거주자-전일(월)금액']=df3['거주자-전일(월)금액'].astype(int)

In [118]:
df3['법정읍면동명칭']=df3['법정읍면동명칭'].map(dong_dic)

C:\Users\shjo\AppData\Local\Temp\ipykernel_11476\4100649152.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['법정읍면동명칭']=df3['법정읍면동명칭'].map(dong_dic)

In [120]:
df3.isnull().sum()

주차장고유값         0
주차장명           0
경도             0
위도             0
거주자-전일(월)금액    0
법정읍면동명칭        0
dtype: int64

In [121]:
df3

       주차장고유값             주차장명          경도         위도  거주자-전일(월)금액  법정읍면동명칭
0     5533775      광장동IoT공유주차장  127.110864  37.550973        40000    10400
1     5533773      광장동IoT공유주차장  127.111042  37.551358        40000    10400
2     5533772      광장동IoT공유주차장  127.111026  37.551333        40000    10400
3     4759402        102 노상주차장  127.111104  37.551381        40000    10400
4     4755783     102 거주자우선주차장  127.111022  37.551256        40000    10400
...       ...              ...         ...        ...          ...      ...
1579  5532177  526-34 거주자우선주차장  127.075151  37.539111        40000    10700
1580  5532176  526-34 거주자우선주차장  127.075133  37.539047        40000    10700
1581  5532175  526-34 거주자우선주차장  127.075126  37.539000        40000    10700
1582  5532174  526-34 거주자우선주차장  127.075121  37.538948        40000    10700
1583  5532140  526-34 거주자우선주차장  127.075122  37.538909        40000    10700

[1584 rows x 6 columns]

In [ ]:
df3.to_csv(f"/{Path2}/서울특별시 광진구_야간개방주차장_20221227.csv", index = False)

***

# 5. 광진구 장애인전용주차장 과태료 현황

In [ ]:
df4 = pd.read_csv(f"/{Path}/서울특별시 광진구_2022년 장애인전용주차구역 과태료 부과 현황_20230207.csv", encoding = 'cp949')

In [ ]:
df4

     연도     시도  시군구  과태료 부과 건수     과태료 금액
0  2022  서울특별시  광진구       1617  145160000

***

 # 6. 광진구 불법주정차 cctv위치 정보

In [ ]:
df5 = pd.read_csv(f"/{Path}/서울특별시 광진구_불법주정차 위반 단속 CCTV 위치정보_20220502.csv", encoding = 'cp949')

In [ ]:
df5

,고정형CCTV지번주소,위도,경도,자치구,단속지점명,현장구분
0,서울 광진구 광장동 334-2,37.547790,127.106990,광진구,모두투어앞,불법주정차구역
1,서울 광진구 광장동 445-3,37.543799,127.102410,광진구,광현교회 앞,불법주정차구역
2,서울 광진구 구의동 135,37.549593,127.081780,광진구,아차산역 5번출구 앞,불법주정차구역
3,서울 광진구 군자동 503,37.548609,127.071072,광진구,두산위브 앞,불법주정차구역
4,서울 광진구 구의동 66-62,37.545348,127.088420,광진구,국민은행 앞,불법주정차구역
5,서울 광진구 구의동 68-29,37.545976,127.086327,광진구,구의사거리,불법주정차구역
6,서울 광진구 구의동 546-1,37.533558,127.093389,광진구,리젠트오피스텔건너편,불법주정차구역
7,서울 광진구 구의동 546-11,37.535562,127.093359,광진구,지너스타워 주차장 앞,불법주정차구역
8,서울 광진구 구의동 611,37.538347,127.096620,광진구,현대2단지아파트 앞,불법주정차구역
9,서울 광진구 구의동 546-6,37.535668,127.094522,광진구,강변역 1번 출구,불법주정차구역
10,서울 광진구 구의동 546-6,37.535668,127.094522,광진구,강변역 4번 출구,불법주정차구역
11,서울 광진구 구의동 547-7,37.533556,127.092096,광진구,동서울터미널 주차장 앞,불법주정차구역
12,서울 광진구 구의동 548-1,37.537558,127.097672,광진구,프라임아파트 정문(213동),불법주정차구역
13,서울 광진구 구의동 593-15,37.535074,127.091264,광진구,강변 스파랜드 앞,불법주정차구역
14,서울 광진구 군자동 364-15,37.551315,127.071524,광진구,노인종합복지관 앞,불법주정차구역
15,서울 광진구 군자동 477-18,37.556333,127.078490,광진구,군자 CGV 앞,불법주정차구역
16,서울 광진구 군자동 466-17,37.558614,127.075273,광진구,군자빌딩,불법주정차구역
17,서울 광진구 능동 18-10,37.546696,127.078784,광진구,어린이대공원 정문,불법주정차구역
18,서울 광진구 능동 247-11,37.554604,127.085645,광진구,아씨방 앞,불법주정차구역
19,서울 광진구 능동 315-8,37.552324,127.077209,광진구,서울시민안전체험관 앞,불법주정차구역
20,서울 광진구 군자동 249,37.551472,127.076016,광진구,세종대정문 택시승강장,불법주정차구역
21,서울 광진구 자양동 606-11,37.532199,127.079078,광진구,파리바게트 앞,불법주정차구역
22,서울 광진구 자양동 8-24,37.541005,127.067410,광진구,건대역약국 앞,불법주정차구역
23,서울 광진구 중곡동 165-6,37.563888,127.082772,광진구,중곡지구대 앞,불법주정차구역
24,서울 광진구 중곡동 247-6,37.563661,127.078227,광진구,MB모터스 옆,불법주정차구역
25,서울 광진구 중곡동 610-8,37.561855,127.074665,광진구,태양주유소 앞,불법주정차구역
26,서울 광진구 중곡동 161-44,37.558383,127.080377,광진구,고신경정신과의원 앞,불법주정차구역
27,서울 광진구 중곡동 79-9,37.557599,127.088160,광진구,우리은행 앞,불법주정차구역
28,서울 광진구 중곡동 115-9,37.552550,127.089722,광진구,공원약국 앞,불법주정차구역
29,서울 광진구 화양동 48-14,37.541118,127.067913,광진구,건대입구 1번 출구 앞,불법주정차구역
30,서울 광진구 화양동 4-20,37.540663,127.071413,광진구,건대입구 3번 출구 앞,불법주정차구역
31,서울 광진구 화양동 5-3,37.542164,127.071299,광진구,건대분수광장 건너편,불법주정차구역
32,서울 광진구 화양동 5-84,37.540849,127.070766,광진구,건국대병원 맞은편,불법주정차구역
33,서울 광진구 중곡동 231-2,37.565014,127.080397,광진구,신성그랜드타워 앞,불법주정차구역
34,서울 광진구 자양동 662-2,37.531472,127.083548,광진구,성자초등학교 옆,불법주정차구역
35,서울 광진구 자양동 679-30,37.532018,127.085371,광진구,한국보건의료인 국가시험원 앞,불법주정차구역
36,서울 광진구 중곡동 168-8,37.567767,127.084713,광진구,중곡문화체육센터 앞,불법주정차구역
37,서울 광진구 광장동 565,37.541929,127.099670,광진구,광장 힐스테이 상가 건너편,불법주정차구역
38,서울 광진구 자양동 239-1,37.536615,127.062808,광진구,올포유 앞,불법주정차구역
39,서울 광진구 구의동 253-15,37.544137,127.084627,광진구,구의동 대림바스플랜 앞,불법주정차구역
40,서울 광진구 구의동 252-16,37.538247,127.083852,광진구,구의동 웰츠타워 앞,불법주정차구역
41,서울 광진구 구의동 17-1,37.554630,127.096635,광진구,구의동 금성빌라 앞,불법주정차구역
42,서울 광진구 자양동 855,37.533363,127.068534,광진구,이튼타워리버3차 앞,불법주정차구역
43,서울 광진구 군자동 374-4,37.547781,127.071974,광진구,광진광장,불법주정차구역
44,서울 광진구 자양동 627-21,37.535226,127.084067,광진구,자양동 동제한의원 앞,불법주정차구역
45,서울 광진구 중곡4동 18-29,37.565215,127.086605,광진구,국립건강정신센터 건너(어린이보호구역),불법주정차구역
46,서울 광진구 자양동 694-1,37.532404,127.089536,광진구,성동초등학교(어린이보호구역),불법주정차구역
47,서울 광진구 자양동 547-64,37.537479,127.068305,광진구,CU 자양써밋플레이스점 앞,불법주정차구역
48,서울 광진구 화양동 303-9,37.543145,127.080322,광진구,구의초등학교 앞(어린이보호구역),불법주정차구역
49,서울 광진구 중곡동 649-3,37.557677,127.078754,광진구,군자역1번출구 명품갤러리,불법주정차구역
50,서울 광진구 중곡동 157-4,37.557062,127.080312,광진구,군자역4번출구 심서방 앞,불법주정차구역
51,서울 광진구 능동 220-4,37.556754,127.080131,광진구,군자역5번출구 가구할인매장 앞,불법주정차구역
52,서울 광진구 군자동 478-1,37.557303,127.078700,광진구,군자역8번부근 앞,불법주정차구역

***

# 7. 광진구 주정차단속현황

In [ ]:
df6 = pd.read_csv(f"/{Path}/서울특별시 광진구_주정차단속현황_20220610.csv", encoding = 'cp949')

In [ ]:
df6

,단속일시,단속원금,단속동,단속장소,위반내용,견인지시,데이터기준일자
0,2015-01-01 06:44,40000,화양동,119-4,주정차금지,견인처리,2022-06-10
1,2015-01-01 07:01,40000,화양동,건대입구1번출구앞,32조내지 34조위반,미견인,2022-06-10
2,2015-01-01 07:24,50000,구의동,동서울터미널 주차장앞,32조내지 34조위반,미견인,2022-06-10
3,2015-01-01 08:00,40000,화양동,건대입구1번출구앞,32조내지 34조위반,미견인,2022-06-10
4,2015-01-01 08:15,40000,화양동,건대입구1번출구앞,32조내지 34조위반,미견인,2022-06-10
...,...,...,...,...,...,...,...
473069,2022-05-31 21:32,40000,구의동,지너스타워 주차장 앞,횡단보도,미견인,2022-06-10
473070,2022-05-31 21:46,40000,구의동,서울특별시 광진구 자양로22길 24,횡단보도,미견인,2022-06-10
473071,2022-05-31 21:46,40000,구의동,서울특별시 광진구 구의로16길 30,교통소통장애,미견인,2022-06-10
473072,2022-05-31 22:51,40000,광장동,328-2,보도,미견인,2022-06-10
473073,2022-05-31 23:36,40000,군자동,서울 광진구 군자동 498,보도,미견인,2022-06-10

***

# 8. 광진구 부설주차장

In [130]:
df7 = pd.read_csv(f"{Path1}/(제출)4-1A.부설주차장_221212.csv", encoding = 'utf-8')

# 8-1. 전처리

In [124]:
df7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15820 entries, 0 to 15819
Data columns (total 62 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   일련번호(no)                                    15820 non-null  int64
 1   주차장고유값(pl_id)                               15820 non-null  int64
 2   주차장이름(pl_nm)                                15820 non-null  object
 3   구코드(sgg_code)                               15820 non-null  int64
 4   법정동코드(bemd_code)                            15820 non-null  int64
 5   산구분(land_registered)                        15820 non-null  object
 6   번지(beonji)                                  15820 non-null  int64
 7   호(ho)                                       15820 non-null  int64
 8   주소(지번)(lot_num_address)                     15820 non-null  object
 9   새주소-도로명(road_nm_address)                    15817 non-null  object
 10  새주소-건물번호(bld_num)                           15817 non-null  object
 11  일반인이용(pl_open_public)                       15820 non-null  object
 12  유무료(pl_fee)                                 15820 non-null  object
 13  일반-기본단위시간(pl_basic_rate_min)                15820 non-null  int64
 14  일반-기본단위금액(pl_basic_rate_amt)                15820 non-null  int64
 15  일반-추가단위시간(pl_addi_rate_min)                 15820 non-null  int64
 16  일반-추가단위금액(pl_addi_rate_amt)                 15820 non-null  int64
 17  일반-1일(전일)(pl_allday_pass_amt)               15820 non-null  int64
 18  일반-1월(정기권)(pl_month_pass_amt)               15820 non-null  int64
 19  주차요금 지불방식(pl_payment_option)                15820 non-null  object
 20  부제시행(bool_not_driving_system)               15820 non-null  object
 21  평일시작시간(pl_weekday_start_time)               15820 non-null  int64
 22  평일종료시간(pl_weekday_end_time)                 15820 non-null  int64
 23  토요일시작시간(pl_sat_start_time)                  15820 non-null  int64
 24  토요일종료시간(pl_sat_end_time)                    15820 non-null  int64
 25  공휴일시작시간(pl_holiday_start_time)              15820 non-null  int64
 26  공휴일종료시간(pl_holiday_end_time)                15820 non-null  int64
 27  건물명(pl_building_nm)                         5570 non-null   object
 28  건축물층수-지하(pl_num_floor_underground)          15820 non-null  int64
 29  건축물층수-지상(pl_num_floor_aboveground)          15820 non-null  int64
 30  계획주차면수(pl_num_space_planned)                14894 non-null  float64
 31  전용주차구획-장애인(pl_num_disabled_private)         15227 non-null  float64
 32  전용주차구획-경차(pl_num_compact_private)           15201 non-null  float64
 33  전용주차구획-기타(pl_num_other_private)             15181 non-null  float64
 34  전용주차구획-여성우선(pl_num_women_only)              14969 non-null  float64
 35  주차장연락처(pl_contact_num)                      7 non-null      object
 36  운영방식(operation_type)                        15820 non-null  object
 37  할인정책-장애인(pl_discount_disabled)              15820 non-null  int64
 38  할인정책-경차(pl_discount_compact)                15820 non-null  int64
 39  할인정책-다자녀가정(두자녀)(pl_discount_2children)      15820 non-null  int64
 40  할인정책-다자녀가정(세자녀)(pl_discount_3children)      15820 non-null  int64
 41  할인정책-국가유공자(pl_discount_person_merit)        15820 non-null  int64
 42  할인정책-10부제참여차량(pl_discount_ten_part_system)  15820 non-null  int64
 43  할인정책-요일제차량(pl_discount_weekdayly)           15820 non-null  int64
 44  할인정책-기타할인율(pl_discount_other_percent)       15820 non-null  int64
 45  할인정책-기타대상(pl_discount_other_target)         15820 non-null  int64
 46  공유주차장구분(shared_parkinglot)                  15820 non-null  object
 47  시간외개방(open_after_op_time)                   15820 non-null  object
 48  전용주차구획-전기차(pl_num_elctronic_only)           15197 non-null  float64
 49  전용주차구획-나눔카(pl_num_shared_car)               15193 non-null  float64
 50  평일개방여부(open_weekday)                        15820 non-null  object
 51  토요일개방여부(open_sat)                           15820 non-null  object
 52  공휴일개방여부(open_holiday)                       15820 non-null  object
 53  첨두시-주간-시작시간(pl_peak_day_start)              15820 non-null  int64
 54  첨두시-주간-종료시간(pl_peak_day_end)                15820 non-null  int64
 55  첨두시-주간-대수(pl_peak_day_num)                  24 non-null     float64
 56  첨두시-야간-시작시간(pl_peak_night_start)            15820 non-null  int64
 57  첨두시-야간-종료시간(pl_peak_night_end)              15820 non-null  int64
 58  첨두시-야간-대수(pl_peak_night_num)                13 non-null     float64
 59  경도(logitude)                                15820 non-null  float64
 60  위도(latitude)                                15820 non-null  float64
 61  최종작성일(final_end_dt)                         15820 non-null  object
dtypes: float64(11), int64(33), object(18)
memory usage: 7.5+ MB

# 8-2 . 필요없는 (속성)열 제거

In [131]:
#사용하는 열만 추출
df7 = df7[[ '주차장고유값(pl_id)',
            '주차장이름(pl_nm)',                 
            '일반-1일(전일)(pl_allday_pass_amt)',                                              
            '계획주차면수(pl_num_space_planned)',
            '법정동코드(bemd_code)',
            '경도(logitude)',
            '위도(latitude)']]

In [132]:
#nan값 행 확인
df7[df7["계획주차면수(pl_num_space_planned)"].isnull()]

,주차장고유값(pl_id),주차장이름(pl_nm),일반-1일(전일)(pl_allday_pass_amt),계획주차면수(pl_num_space_planned),법정동코드(bemd_code),경도(logitude),위도(latitude)
2,4272953,능동로32길 106-05 주차장,0,NaN,10200,127.083952,37.553057
7,4862783,능동로34길 117-02 주차장,0,NaN,10200,127.085673,37.553559
8,4864251,능동로32길 062-02 주차장,0,NaN,10200,127.081685,37.554010
9,4869965,천호대로118길 033-05 주차장,0,NaN,10200,127.085122,37.553163
14,4897240,천호대로116길 053-00 주차장,0,NaN,10200,127.083107,37.552883
...,...,...,...,...,...,...,...
14760,5017188,영화사로3길 013-00 주차장,0,NaN,10100,127.090726,37.557560
14763,5009481,영화사로3길 027-00 주차장,0,NaN,10100,127.091236,37.558075
14766,5066113,영화사로3길 005-00 주차장,0,NaN,10100,127.090410,37.557314
14767,5017187,영화사로3길 007-00 주차장,0,NaN,10100,127.090533,37.557381
14913,5015234,긴고랑로 203-00 주차장,0,NaN,10100,127.095679,37.561431

In [133]:
df7.isnull().sum()

주차장고유값(pl_id)                      0
주차장이름(pl_nm)                       0
일반-1일(전일)(pl_allday_pass_amt)      0
계획주차면수(pl_num_space_planned)     926
법정동코드(bemd_code)                   0
경도(logitude)                       0
위도(latitude)                       0
dtype: int64

In [134]:
#nan값 0으로 바꾸기
df7 = df7.dropna().reset_index(drop=True)

In [137]:
df7=df7[df7['계획주차면수(pl_num_space_planned)']!=0]

In [138]:
df7

,주차장고유값(pl_id),주차장이름(pl_nm),일반-1일(전일)(pl_allday_pass_amt),계획주차면수(pl_num_space_planned),법정동코드(bemd_code),경도(logitude),위도(latitude)
0,4272844,능동로32길 073-00 주차장,0,2.0,10200,127.082462,37.554053
1,4272868,M캐슬 가을 주차장,0,7.0,10200,127.081944,37.553433
2,4273230,에스에치빌 주차장,0,6.0,10200,127.086620,37.553290
3,4849415,어린이대공원 구의문,0,315.0,10200,127.085488,37.542811
4,4856796,천호대로114길 021-00 주차장,0,4.0,10200,127.082645,37.554738
...,...,...,...,...,...,...,...
14888,5110677,천호대로129길 079-00 주차장,0,2.0,10100,127.093003,37.554804
14889,5127545,대성예가 주차장,0,4.0,10100,127.092491,37.554612
14890,5528613,자양로51길 030-05 주차장,0,2.0,10100,127.092247,37.554447
14891,5528734,천호대로127길 038-00 주차장,0,4.0,10100,127.090747,37.554151
14892,5528839,자양로45길 079-00 주차장,0,5.0,10100,127.089799,37.554584

In [ ]:
#전처리 데이터 저장
df7.to_csv(f"/{Path2}/(제출)4-1A.부설주차장_221212.csv", index = False)

***

# 9. 광진구 노상주차장(제외)

In [139]:
df8 = pd.read_csv(f"{Path1}/(제출)4-1B.노상주차장_221212.csv", encoding = 'utf-8')

# 9-1. 전처리

In [140]:
df8.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2530 entries, 0 to 2529
Data columns (total 54 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   일련번호(no)                                    2530 non-null   int64
 1   주차장고유값(pl_id)                               2530 non-null   int64
 2   지번주차장이름(pl_nm)                              2530 non-null   object
 3   구코드(sgg_code)                               2530 non-null   int64
 4   법정동코드(bemd_code)                            2530 non-null   int64
 5   산구분(land_registered)                        2530 non-null   object
 6   공유주차장구분(shared_parkinglot)                  9 non-null      object
 7   번지(beonji)                                  2530 non-null   int64
 8   호(ho)                                       2530 non-null   int64
 9   주소(지번)(lot_num_address)                     2530 non-null   object
 10  새주소-도로명(road_nm_address)                    2530 non-null   object
 11  새주소-건물번호(bld_num)                           2478 non-null   object
 12  소유주체(possessor)                             2530 non-null   int64
 13  급지(pl_grade)                                2530 non-null   int64
 14  유무료(pl_fee)                                 2530 non-null   object
 15  평일시작시간(pl_weekday_start_time)               2530 non-null   int64
 16  평일종료시간(pl_weekday_end_time)                 2530 non-null   int64
 17  토요일시작시간(pl_sat_start_time)                  2530 non-null   int64
 18  토요일종료시간(pl_sat_end_time)                    2530 non-null   int64
 19  공휴일시작시간(pl_holiday_start_time)              2530 non-null   int64
 20  공휴일종료시간(pl_holiday_end_time)                2530 non-null   int64
 21  기본단위시간(pl_basic_rate_min)                   2530 non-null   int64
 22  기본단위금액(pl_basic_rate_amt)                   2530 non-null   int64
 23  추가단위시간(pl_addi_rate_min)                    2530 non-null   int64
 24  추가단위금액(pl_addi_rate_amt)                    2530 non-null   int64
 25  1일(전일)금액(pl_allday_pass_amt)                2530 non-null   int64
 26  1월(정기권)금액(pl_month_pass_amt)                2530 non-null   int64
 27  주차요금지불방식(pl_payment_option)                 2530 non-null   object
 28  부제시행(bool_not_driving_system)               2530 non-null   object
 29  운영방식(operation_type)                        2530 non-null   object
 30  구간번호(section)                               2530 non-null   object
 31  구획번호(parcel)                                2530 non-null   object
 32  거주자-주간(월)금액(resident_day_month_amt)         2529 non-null   object
 33  거주자-야간(월)금액(resident_night_month_amt)       2529 non-null   object
 34  거주자-전일(월)금액(resident_allday_month_amt)      2529 non-null   object
 35  거주자-평일시작시간(resident_weekday_start_time)     2530 non-null   int64
 36  거주자-평일종료시간(resident_weekday_end_time)       2530 non-null   object
 37  거주자-토요일시작시간(resident_sat_start_time)        2530 non-null   object
 38  거주자-토요일종료시간(resident_sat_end_time)          2530 non-null   int64
 39  거주자-휴일시작시간(resident_holiday_start_time)     2530 non-null   int64
 40  거주자-휴일종료시간(resident_holiday_end_time)       2530 non-null   int64
 41  할인정책-장애인(pl_discount_disabled)              2530 non-null   object
 42  할인정책-경차(pl_discount_compact)                2530 non-null   object
 43  할인정책-다자녀가정(두자녀)(pl_discount_2children)      2530 non-null   object
 44  할인정책-다자녀가정(세자녀)(pl_discount_3children)      2530 non-null   object
 45  할인정책-국가유공자(pl_discount_person_merit)        2530 non-null   object
 46  할인정책-10부제참여차량(pl_discount_ten_part_system)  2530 non-null   object
 47  할인정책-요일제차량(pl_discount_weekdayly)           2530 non-null   object
 48  할인정책-기타할인율(pl_discount_other_percent)       2530 non-null   object
 49  할인정책-기타대상(pl_discount_other_target)         2529 non-null   object
 50  그룹관리번호(managing_group_no)                   2530 non-null   int64
 51  경도(longitude)                               2530 non-null   float64
 52  위도(latitude)                                2530 non-null   float64
 53  구축기준일(final_end_dt)                         2530 non-null   object
dtypes: float64(2), int64(25), object(27)
memory usage: 1.0+ MB

# 9-2 . 필요없는 (속성)열 제거

In [ ]:
df8 = df8[[ '주차장고유값(pl_id)', 
            '지번주차장이름(pl_nm)',                 
            '1일(전일)금액(pl_allday_pass_amt)',                    
            '법정동코드(bemd_code)',                                
            '경도(longitude)',                            
            '위도(latitude)']]

In [ ]:
#nan값 행 확인
df8[df8["위도(latitude)"].isnull()]

Empty DataFrame
Columns: [일련번호(no), 주차장고유값(pl_id), 지번주차장이름(pl_nm), 구코드(sgg_code), 법정동코드(bemd_code), 주소(지번)(lot_num_address), 기본단위시간(pl_basic_rate_min), 기본단위금액(pl_basic_rate_amt), 추가단위시간(pl_addi_rate_min), 추가단위금액(pl_addi_rate_amt), 1일(전일)금액(pl_allday_pass_amt), 1월(정기권)금액(pl_month_pass_amt), 거주자-주간(월)금액(resident_day_month_amt), 거주자-야간(월)금액(resident_night_month_amt), 거주자-전일(월)금액(resident_allday_month_amt), 경도(longitude), 위도(latitude)]
Index: []

In [ ]:
#nan값 0으로 바꾸기
df8["거주자-주간(월)금액(resident_day_month_amt)"] = df8["거주자-주간(월)금액(resident_day_month_amt)"].fillna(0)
df8["거주자-야간(월)금액(resident_night_month_amt)"] = df8["거주자-야간(월)금액(resident_night_month_amt)"].fillna(0)
df8["거주자-전일(월)금액(resident_allday_month_amt)"] = df8["거주자-전일(월)금액(resident_allday_month_amt)"].fillna(0)

In [ ]:
df8

,주차장고유값(pl_id),지번주차장이름(pl_nm),기본단위시간(pl_basic_rate_min),기본단위금액(pl_basic_rate_amt),추가단위시간(pl_addi_rate_min),추가단위금액(pl_addi_rate_amt),1일(전일)금액(pl_allday_pass_amt),1월(정기권)금액(pl_month_pass_amt),거주자-주간(월)금액(resident_day_month_amt),거주자-야간(월)금액(resident_night_month_amt),거주자-전일(월)금액(resident_allday_month_amt),경도(longitude),위도(latitude)
0,4758432,249-6 노상주차장,0,0,0,0,0,0,30000,20000,40000,127.077648,37.555295
1,4735321,16-81 노상주차장,0,0,0,0,0,0,30000,20000,40000,127.069443,37.544867
2,4756802,16-93 노상주차장,0,0,0,0,0,0,30000,20000,40000,127.069553,37.544947
3,4838021,16-35 노상주차장,0,0,0,0,0,0,30000,20000,40000,127.069842,37.545087
4,4736667,32-12 거주자우선주차장,0,0,0,0,0,0,30000,20000,40000,127.067637,37.546392
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2525,5544300,송림기사식당길A노상공영주차장,5,200,0,0,0,90000,0,0,0,127.076742,37.536322
2526,5544301,송림기사식당길A노상공영주차장,5,200,0,0,0,90000,0,0,0,127.076764,37.536365
2527,5547887,596-7 노상주차장,0,0,0,0,0,0,30000,20000,40000,127.078734,37.530932
2528,5547888,다성시티빌앞주차장,0,0,0,0,0,0,30000,20000,40000,127.078542,37.530415
2529,5548085,601-15 노상주차장,0,0,0,0,0,0,30000,20000,40000,127.076432,37.532366

In [ ]:
#전처리 데이터 저장
df8.to_csv(f"/{Path2}/(제출)4-1B.노상주차장_221212.csv", index = False)

***

# 10. 광진구 노외주차장

In [145]:
df9 = pd.read_csv(f"{Path1}/(제출)4-1C.노외주차장_221213.csv", encoding = 'utf-8')

# 10-1. 전처리

In [146]:
df9.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 257 entries, 0 to 256
Data columns (total 81 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   일련번호(no)                                    62 non-null     float64
 1   주차장고유값(pl_id)                               62 non-null     float64
 2   주차장이름(pl_nm)                                62 non-null     object
 3   구코드(sgg_code)                               62 non-null     float64
 4   법정동코드(bemd_code)                            62 non-null     float64
 5   산구분(land_registered)                        62 non-null     object
 6   번지(beonji)                                  62 non-null     float64
 7   호(ho)                                       62 non-null     float64
 8   주소(지번)(lot_num_address)                     62 non-null     object
 9   새주소-도로명(road_nm_address)                    62 non-null     object
 10  새주소-건물번호(bld_num)                           35 non-null     object
 11  급지(pl_grade)                                62 non-null     float64
 12  공유주차장구분(shared_parkinglot)                  62 non-null     object
 13  유무료(pl_fee)                                 62 non-null     object
 14  평일시작시간(pl_weekday_start_time)               62 non-null     float64
 15  평일종료시간(pl_weekday_end_time)                 62 non-null     float64
 16  토요일시작시간(pl_sat_start_time)                  62 non-null     float64
 17  토요일종료시간(pl_sat_end_time)                    62 non-null     float64
 18  공휴일시작시간(pl_holiday_start_time)              62 non-null     float64
 19  공휴일종료시간(pl_holiday_end_time)                62 non-null     float64
 20  기본단위시간(pl_basic_rate_min)                   62 non-null     float64
 21  기본단위금액(pl_basic_rate_amt)                   62 non-null     float64
 22  추가단위시간(pl_addi_rate_min)                    62 non-null     float64
 23  추가단위금액(pl_addi_rate_amt)                    62 non-null     float64
 24  1일(전일)금액(pl_allday_pass_amt)                62 non-null     float64
 25  1월(정기권)금액(pl_month_pass_amt)                62 non-null     float64
 26  주차요금지불방식(pl_payment_option)                 62 non-null     object
 27  부제시행(bool_not_driving_system)               62 non-null     object
 28  일반인이용(pl_open_public)                       62 non-null     object
 29  상호(own_nm)                                  8 non-null      object
 30  주차면수-대시민(pl_area_citizen)                   62 non-null     float64
 31  주차면수-평면식(pl_area_plane)                     62 non-null     float64
 32  주차면수-자주식-면수(pl_area_self_area)              62 non-null     float64
 33  주차면수-자주식-층(pl_area_self_floor)              62 non-null     float64
 34  주차면수-자주식-단(pl_area_self_step)               62 non-null     float64
 35  주차면수-기계식-면수(pl_area_mechanic_area)          62 non-null     float64
 36  주차면수-기계식-층(pl_area_mechanic_floor)          62 non-null     float64
 37  주차면수-기계식-단(pl_area_mechanic_step)           62 non-null     float64
 38  기계식주차장현황-계(pl_mechanic_total)               62 non-null     float64
 39  기계식주차장현황-2단식(pl_mechanic_second_step)       62 non-null     float64
 40  기계식주차장현황-다단식(pl_mechanic_multi_step)        62 non-null     float64
 41  기계식주차장현황-수평순환식(pl_mechanic_horizon)         62 non-null     float64
 42  기계식주차장현황-수직순환식(pl_mechanic_vertical)        62 non-null     float64
 43  기계식주차장현황-기타(pl_mechanic_etc)                62 non-null     float64
 44  전용주차구획-장애인(pl_num_disabled_private)         62 non-null     float64
 45  전용주차구획-경차(pl_num_compact_private)           62 non-null     float64
 46  전용주차구획-기타(pl_num_other_private)             61 non-null     float64
 47  거주자우선주차-주간(월)(resident_day_month_amt)       62 non-null     float64
 48  거주자우선주차-야간(월)(resident_night_month_amt)     62 non-null     float64
 49  거주자우선주차-전일(월)(resident_allday_month_amt)    62 non-null     float64
 50  거주자-평일시작시간(resident_weekday_start_time)     62 non-null     float64
 51  거주자-평일종료시간(resident_weekday_end_time)       62 non-null     float64
 52  거주자-토요일시작시간(resident_sat_start_time)        62 non-null     float64
 53  거주자-토요일종료시간(resident_sat_end_time)          62 non-null     float64
 54  거주자-공휴일시작시간(resident_holiday_start_time)    62 non-null     float64
 55  거주자-공휴일종료시간(resident_holiday_end_time)      62 non-null     float64
 56  운영방식(operation_type)                        62 non-null     object
 57  전용주차구획-여성(pl_num_women_only)                62 non-null     float64
 58  주차장연락처(pl_contact_num)                      5 non-null      object
 59  할인정책-장애인(pl_discount_disabled)              62 non-null     float64
 60  할인정책-경차(pl_discount_compact)                62 non-null     float64
 61  할인정책-다자녀가정(두자녀)(pl_discount_2children)      62 non-null     float64
 62  할인정책-다자녀가정(세자녀)(pl_discount_3children)      62 non-null     float64
 63  할인정책-국가유공자(pl_discount_person_merit)        62 non-null     float64
 64  할인정책-10부제참여차량(pl_discount_ten_part_system)  62 non-null     float64
 65  할인정책-요일제차량(pl_discount_weekdayly)           62 non-null     float64
 66  할인정책-기타할인율(pl_discount_other_percent)       62 non-null     float64
 67  할인정책-기타대상(pl_discount_other_target)         62 non-null     object
 68  특이사항(specific)                              4 non-null      object
 69  시간외개방(open_after_op_time)                   62 non-null     object
 70  전용주차구획-전기차(pl_num_elctronic_only)           61 non-null     float64
 71  전용주차구획-나눔카(pl_num_shared_car)               59 non-null     float64
 72  첨두시-주간-시작시간(pl_peak_day_start)              62 non-null     float64
 73  첨두시-주간-종료시간(pl_peak_day_end)                62 non-null     float64
 74  첨두시-주간-대수(pl_peak_day_num)                  3 non-null      float64
 75  첨두시-야간-시작시간(pl_peak_night_start)            62 non-null     float64
 76  첨두시-야간-종료시간(pl_peak_night_end)              62 non-null     float64
 77  첨두시-야간-대수(pl_peak_night_num)                6 non-null      float64
 78  경도(longitude)                               62 non-null     float64
 79  위도(latitude)                                62 non-null     float64
 80  최종작성일(final_end_dt)                         62 non-null     object
dtypes: float64(64), object(17)
memory usage: 162.8+ KB

In [147]:
df9

,일련번호(no),주차장고유값(pl_id),주차장이름(pl_nm),구코드(sgg_code),법정동코드(bemd_code),산구분(land_registered),번지(beonji),호(ho),주소(지번)(lot_num_address),새주소-도로명(road_nm_address),...,전용주차구획-나눔카(pl_num_shared_car),첨두시-주간-시작시간(pl_peak_day_start),첨두시-주간-종료시간(pl_peak_day_end),첨두시-주간-대수(pl_peak_day_num),첨두시-야간-시작시간(pl_peak_night_start),첨두시-야간-종료시간(pl_peak_night_end),첨두시-야간-대수(pl_peak_night_num),경도(longitude),위도(latitude),최종작성일(final_end_dt)
0,1.0,4847399.0,중곡2동주차장,11215.0,10100.0,임야도 등록,133.0,10.0,서울특별시 광진구 중곡동 133-10,도로명주소없음,...,0.0,0.0,0.0,NaN,0.0,0.0,NaN,127.084000,37.556402,2022-11-25
1,2.0,4847403.0,새오름,11215.0,10100.0,임야도 등록,143.0,70.0,서울특별시 광진구 중곡동 143-70,용마산로8마길,...,0.0,0.0,0.0,NaN,0.0,0.0,NaN,127.090848,37.561311,2022-11-25
2,3.0,4847409.0,중곡4동주차장,11215.0,10100.0,임야도 등록,87.0,14.0,서울특별시 광진구 중곡동 87-14,영화사로5길,...,0.0,0.0,0.0,NaN,0.0,0.0,NaN,127.091839,37.557057,2022-11-25
3,4.0,4847412.0,용마산남측거주자주차장,11215.0,10100.0,임야도 등록,69.0,2.0,서울특별시 광진구 중곡동 69-2,용마산로8길,...,0.0,0.0,0.0,NaN,0.0,0.0,NaN,127.092091,37.559210,2022-11-25
4,5.0,4847415.0,중곡3동주민센터,11215.0,10100.0,임야도 등록,684.0,11.0,서울특별시 광진구 중곡동 684,동일로76가길,...,0.0,0.0,0.0,NaN,0.0,0.0,NaN,127.079924,37.568681,2022-11-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
253,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
255,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
256,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 10-2 . 필요없는 (속성)열 제거

In [148]:
df9 = df9[[ '주차장고유값(pl_id)', 
            '주차장이름(pl_nm)',                                            
            '주차면수-평면식(pl_area_plane)',                                      
            '1일(전일)금액(pl_allday_pass_amt)',
            '법정동코드(bemd_code)',                                               
            '경도(longitude)',                            
            '위도(latitude)']]

In [149]:
df9 = df9[0:61]

In [175]:
df9

,주차장고유값(pl_id),주차장이름(pl_nm),주차면수-평면식(pl_area_plane),1일(전일)금액(pl_allday_pass_amt),법정동코드(bemd_code),경도(longitude),위도(latitude)
0,4847399,중곡2동주차장,22.0,0.0,10100,127.084000,37.556402
1,4847403,새오름,6.0,0.0,10100,127.090848,37.561311
2,4847409,중곡4동주차장,19.0,0.0,10100,127.091839,37.557057
3,4847412,용마산남측거주자주차장,25.0,0.0,10100,127.092091,37.559210
4,4847415,중곡3동주민센터,22.0,0.0,10100,127.079924,37.568681
...,...,...,...,...,...,...,...
56,4848341,화양동마을마당,6.0,0.0,10700,127.076139,37.545201
57,4848101,광진광장공영주차장,33.0,120000.0,10900,127.073259,37.547695
58,4848102,군자동거주자전용야외주차장,12.0,0.0,10900,127.076563,37.553993
59,4849002,동산교회옆부지,10.0,0.0,10900,127.075861,37.555515
60,4849003,동원,35.0,15000.0,10900,127.075623,37.554876

In [176]:
df9.isnull().sum()

주차장고유값(pl_id)                   0
주차장이름(pl_nm)                    0
주차면수-평면식(pl_area_plane)         0
1일(전일)금액(pl_allday_pass_amt)    0
법정동코드(bemd_code)                0
경도(longitude)                   0
위도(latitude)                    0
dtype: int64

In [174]:
#nan값 행 확인
df9['주차장고유값(pl_id)']=df9['주차장고유값(pl_id)'].astype(int)
df9['법정동코드(bemd_code)']=df9['법정동코드(bemd_code)'].astype(int)

In [ ]:
#전처리 데이터 저장
df9.to_csv(f"/{Path2}/(제출)4-1C.노외주차장_221213.csv", index = False)

***